name: 'deploy to AWS S3'
description: 'deploy a stastic wwebsite via AWS s3'
inputs:
  bucket:
    description: 'the s3 bucket name'
    required: true
  bucket-region:
    description: 'region for the bucket'
    required: false
    default: 'us-east-1'
  dist-folder:
    description: 'the folder containing the deployabl files'
    required: true
runs:
  using: 'node16'
  #pre:
  main: './main.js'
  #post:
