name: 'get & cache dependencies'
#actions are not workflows are part of workflows that is why you don't add a ON key
description: 'get the dependencies (via npm) and cache them.'
runs:
  using: 'composite' #this tells github this is a custome action
  steps:
    - name: Cache dependencies
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci
      shell: bash
